#!/usr/bin/env bash

set -e

fly --target concourse.scottmuc.com set-team \
  --team-name sandbox \
  --config <(cat <<'EOF'
roles:
  - name: owner
    github:
      users:
        - scottmuc

  - name: member
    github:
      users:
        - mrdavidlaing
        - ninabohm
        - p-b-j
        - totherme
EOF
)
