#!/usr/bin/env bash

set -e

fly --target concourse.scottmuc.com set-team \
  --team-name smootz-gmbh \
  --config <(cat <<'EOF'
roles:
  - name: owner
    github:
      users:
        - scottmuc

    local:
      users:
        - smootz

  - name: member
    local:
      users:
        - nina

    github:
      users:
        - ninabohm
EOF
)
