tap 'neovim/neovim'
brew 'neovim'

brew 'autojump'
brew 'chruby'

# This is used to managed the encryption of this repo
brew 'git-crypt'

# Needed for some coding exercises and also for the terraform-gandi provider
brew 'golang'

# Trying to sign my commits now
brew 'gpg'

brew 'jq'
brew 'mr'
brew 'pstree'

# Why do I need python3?
brew 'python3'

brew 'ruby-install'

# Mainly needed by the infrastructure repo
brew 'terraform@0.12'

brew 'tree'

cask '1password'
cask '1password-cli'

# Experimental
# Terminal is ok for general purpose but I want to experiment with the file based configuration
# of alactritty. Full color support is nice too.
cask 'alacritty'

cask 'brave-browser'
cask 'flycut'
cask 'macdown'
cask 'monodraw'
cask 'selfcontrol'
cask 'shiftit'

cask 'vlc'
