auth_enabled: false

server:
  http_listen_port: 3100
  log_level: warn


common:
  path_prefix: /mnt/vcapstore
  storage:
    filesystem:
      chunks_directory: /mnt/vcapstore/loki/chunks
      rules_directory: /mnt/vcapstore/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h


analytics:
  reporting_enabled: false
