# https://alacritty.org/config-alacritty.html

[general]
import = [ "$THEME_PATH" ]

[font]
size = 12.0
normal = { family = "JetBrainsMono Nerd Font" }

[terminal.shell]
program = "wsl"
args = ["--distribution", "Ubuntu", "--cd", "~"]

[selection]
save_to_clipboard = true
