tap 'neovim/neovim'
brew 'neovim'

brew 'gpg'

# Dependency of `easy-op` and all around useful utility
brew 'jq'

# alacritty is a single pane terminal so need to use tmux for tabs and panes
brew 'tmux'

# Experimental
# Terminal is ok for general purpose but I want to experiment with the file based configuration
# of alactritty. Full color support is nice too.
cask 'alacritty'

cask '1password'
cask '1password-cli'
cask 'shiftit'

# Needed for Bitnami VPN
cask 'tunnelblick'
