tap 'neovim/neovim'
brew 'neovim'

brew 'autojump'

# This is used to managed the encryption of this repo
brew 'git-crypt'

# Trying to sign my commits now
brew 'gpg'

brew 'jq'
brew 'mr'
brew 'pstree'

brew 'tree'

cask '1password'
cask '1password-cli'
cask 'brave-browser'
cask 'iterm2'
cask 'flycut'
cask 'macdown'
cask 'monodraw'
cask 'selfcontrol'
cask 'shiftit'

# there are some issues to make installing virtualbox smoothly
# https://apple.stackexchange.com/questions/372492/virtualbox-installation-failed-on-macos-catalina
# cask 'virtualbox'
cask 'vlc'
