- name: Install fuse packages
  ansible.builtin.apt:
    pkg:
      - exfat-fuse


- name: Create USB mount point
  ansible.builtin.file:
    path: /mnt/usb
    state: directory
    owner: root
    group: root
    mode: '0777'


# UUID=5A47-F8E2 /mnt/usb exfat defaults,auto,users,rw,nofail,umask=000 0 0
- name: Mount Disk
  ansible.posix.mount:
    state: mounted
    path: /mnt/usb
    src: UUID=5A47-F8E2
    fstype: exfat
    opts: defaults,auto,users,rw,nofail,umask=000
