- name: Setup syncthing
  hosts: erebor.middle-earth.internal.

  tasks:
    - name: Ensure syncthing is installed
      become: true
      community.general.pkgng:
        pkg:
          - syncthing


    - name: Create syncthing user
      become: true
      ansible.builtin.user:
        name: syncthing
        shell: /usr/sbin/nologin
        comment: "syncthing service user"
        groups: syncthing
        createhome: false


    - name: Create syncthing directories
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: syncthing
        group: syncthing
        mode: '0700'
      loop:
        - /usr/local/var/mcap/store/syncthing
        - /usr/local/var/mcap/store/syncthing/state
        - /usr/local/var/mcap/store/syncthing/data


    - name: Configure syncthing_user in rc.d
      become: true
      community.general.sysrc:
        name: syncthing_user
        state: present
        value: "syncthing"


    - name: Configure syncthing_home in rc.d
      become: true
      community.general.sysrc:
        name: syncthing_home
        state: present
        value: "/usr/local/var/mcap/store/syncthing/state"


    - name: Enable and syncthing service
      become: true
      ansible.builtin.service:
        name: syncthing
        enabled: true
        state: started


    - name: Configure syncthing
      become: true
      ansible.builtin.copy:
        src: ./files/syncthing.config.xml
        dest: /usr/local/var/mcap/store/syncthing/state/config.xml
        owner: syncthing
        group: syncthing
        mode: '0600'
      notify: Restart syncthing


  handlers:
    - name: Restart syncthing
      become: true
      ansible.builtin.service:
        name: syncthing
        state: restarted

# vim: ft=yaml.ansible
