- name: Completely setup Pippin
  hosts: all
  remote_user: ansible

  tasks:
    # I am uncertain if this belongs in the bootstrap, or in some overarching
    # task file pertaining to networking among other things. I don't know if it
    # really matters that much, but might as well start pondering it now.
    #
    # Turns out this is set when I created the installer image. So this resource
    # might be redundant.
    - name: Set hostname
      become: true
      ansible.builtin.hostname:
        name: pippin


    - name: Securing the machine
      ansible.builtin.include_tasks:
        file: ../tasks/security.yml


    - name: Configure sysctls
      become: true
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      tags: [sysctls]
      loop:
        # https://linuxhint.com/understanding_vm_swappiness/
        - name: vm.swappiness
          value: '1'
        # Disable IPv6
        - name: net.ipv6.conf.all.disable_ipv6
          value: '1'
        - name: net.ipv6.conf.default.disable_ipv6
          value: '1'
        - name: net.ipv6.conf.lo.disable_ipv6
          value: '1'


    - name: Configure syslog forwarding
      tags: logging
      ansible.builtin.include_tasks:
        file: ../tasks/logging.yml
        apply:
          tags: logging


    - name: Install and dhcpd, dns, and network configuration
      tags: lanmanager
      ansible.builtin.include_tasks:
        file: ../tasks/lanmanager.yml
        apply:
          tags: lanmanager


    - name: Configure mounts
      tags: mounts
      ansible.builtin.include_tasks:
        file: ../tasks/mounts.yml
        apply:
          tags: mounts


    - name: Install navidrome
      vars:
        navidrome_version: "0.52.5"
      tags: navidrome
      ansible.builtin.include_tasks:
        file: ../tasks/navidrome.yml
        apply:
          tags: navidrome


    - name: Setup git host
      tags: git
      ansible.builtin.include_tasks:
        file: ../tasks/githost.yml
        apply:
          tags: git


    - name: Install webserver things
      tags: webserver
      ansible.builtin.include_tasks:
        file: ../tasks/webserver.yml
        apply:
          tags: webserver


    - name: Install monitoring
      tags: monitoring
      vars:
        prometheus_version: "2.53.0"
        node_exporter_version: "1.8.1"
      ansible.builtin.include_tasks:
        file: ../tasks/monitoring.yml
        apply:
          tags: monitoring

  handlers:
    # It's important that Systemd reload is defined first here
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html#controlling-when-handlers-run
    #
    # This might not be necessary though... still need to think this through
    - name: Systemd reload
      become: true
      ansible.builtin.systemd:
        daemon_reload: true


    - name: Restart dnsmasq
      become: true
      ansible.builtin.service:
        name: dnsmasq
        state: restarted


    - name: Restart nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted


    - name: Restart navidrome
      become: true
      ansible.builtin.service:
        name: navidrome
        state: restarted


    - name: Restart prometheus
      become: true
      ansible.builtin.service:
        name: prometheus
        state: restarted


    - name: Restart node_exporter
      become: true
      ansible.builtin.service:
        name: node_exporter
        state: restarted


    - name: Restart grafana
      become: true
      ansible.builtin.service:
        name: grafana-server
        state: restarted


    - name: Restart unbound
      become: true
      ansible.builtin.service:
        name: unbound
        state: restarted


    - name: Restart rsyslog
      become: true
      ansible.builtin.service:
        name: rsyslog
        state: restarted


    - name: Reload sshd
      become: true
      ansible.builtin.service:
        name: sshd
        state: reloaded


    - name: Restart fail2ban
      become: true
      ansible.builtin.service:
        name: fail2ban
        state: restarted

    - name: Restart unbound_exporter
      become: true
      ansible.builtin.service:
        name: unbound_exporter
        state: restarted


    - name: Restart dnsmasq_exporter
      become: true
      ansible.builtin.service:
        name: dnsmasq_exporter
        state: restarted


    - name: Restart loki
      become: true
      ansible.builtin.service:
        name: loki
        state: restarted


    - name: Restart promtail
      become: true
      ansible.builtin.service:
        name: promtail
        state: restarted
# vim: ft=yaml.ansible
