- name: Install unbound
  become: true
  ansible.builtin.apt:
    pkg:
      - unbound


- name: Setup unbound log directory
  become: true
  ansible.builtin.file:
    path: /var/log/unbound
    state: directory
    owner: unbound
    group: unbound
    mode: '0775'


- name: Configure logrotate for unbound
  become: true
  ansible.builtin.copy:
    dest: /etc/logrotate.d/unbound
    owner: root
    group: root
    mode: '0644'
    content: |
      /var/log/unbound/*.log {
        weekly
        rotate 7
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
        create 644
        postrotate
          /usr/sbin/unbound-control log_reopen
        endscript
      }


- name: Configure unbound
  become: true
  ansible.builtin.copy:
    dest: /etc/unbound/unbound.conf.d/pi-hole-replacement.conf
    owner: root
    group: root
    mode: '0664'
    content: |
      # https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html
      server:
        interface: 0.0.0.0
        access-control: 192.168.2.0/24 allow
        do-ip6: no
        include: /etc/unbound/blocklist.conf

        # Disable syslog when logging queries to not use all my papertrail quota
        use-syslog: no
        verbosity: 0
        log-queries: yes
        log-replies: yes
        log-tag-queryreply: yes
        log-local-actions: yes
        logfile: /var/log/unbound/unbound.log

        # https://blog.josefsson.org/2015/10/26/combining-dnsmasq-and-unbound/#comment-1399545
        # ^^^ this comment from nearly 10 years ago really helped me figure all this out!

        # The two lines below allow unbound to return private IPs and to ignore
        # the DNSSEC chain of trust for middle-earth.internal.
        private-domain: "middle-earth.internal."
        domain-insecure: "middle-earth.internal."

        private-domain: "2.168.192.in-addr.arpa."
        domain-insecure: "2.168.192.in-addr.arpa."
        local-zone: "2.168.192.in-addr.arpa." transparent

        # All queries related to my LAN's private domain should be forwared
        # to the dnsmasq resolver.
        forward-zone:
          name: "middle-earth.internal."
          forward-addr: 192.168.2.10@5353

        forward-zone:
          name: "2.168.192.in-addr.arpa."
          forward-addr: 192.168.2.10@5353
  notify:
    - Restart unbound


- name: Add blocklist
  become: true
  ansible.builtin.get_url:
    dest: /etc/unbound/blocklist.conf
    owner: root
    group: root
    mode: '0664'
    url: https://raw.githubusercontent.com/scottmuc/dns-zone-blocklist/main/unbound/unbound.blocklist
  notify:
    - Restart unbound


- name: Ensure unbound is running
  become: true
  ansible.builtin.service:
    name: unbound
    state: started
    enabled: true


# - name: Ensure avahi-daemon and isc-dhcp-client are not installed
#   become: true
#   ansible.builtin.apt:
#     pkg:
#       - avahi-daemon
#       - isc-dhcp-client
#     state: absent


# I'm using a USB/ethernet adapter and the interface name is stable because
# it's following the structure enx + mac address
# https://superuser.com/questions/1431018/network-interface-names-via-udev-for-usb-nics
- name: Setup static IP
  become: true
  ansible.builtin.copy:
    dest: /etc/network/interfaces.d/enx00e04c01156b
    owner: root
    group: admin
    mode: '0664'
    content: |
      auto enx00e04c01156b
      allow-hotplug enx00e04c01156b
      iface enx00e04c01156b inet static
      address 192.168.2.11
      netmask 255.255.255.0
      gateway 192.168.2.1
      dns-nameservers 127.0.0.1
      dns-search middle-earth.internal


# - name: Install /etc/resolv.conf
#   become: true
#   ansible.builtin.copy:
#     dest: /etc/resolv.conf
#     owner: root
#     group: root
#     mode: '0644'
#     content: |
#       search middle-earth.internal
#       nameserver 127.0.0.1


# - name: Install /etc/hosts
#   become: true
#   ansible.builtin.copy:
#     dest: /etc/hosts
#     owner: root
#     group: root
#     mode: '0644'
#     content: |
#       127.0.0.1     localhost
#       192.168.2.10  pippin.middle-earth.internal  pippin

# vim: ft=yaml.ansible
