- name: Install node exporter
  vars:
    version: "{{ node_exporter_version }}"
  ansible.builtin.include_tasks:
    file: ../tasks/node_exporter.yml


- name: Install unbound exporter
  ansible.builtin.include_tasks:
    file: ../tasks/unbound_exporter.yml


# vim: ft=yaml.ansible
