- name: Create prometheus user group
  become: true
  ansible.builtin.group:
    name: prometheus
    system: true
    state: present


- name: Create prometheus user
  become: true
  ansible.builtin.user:
    name: prometheus
    system: true
    state: present


- name: Install node exporter
  vars:
    version: "{{ node_exporter_version }}"
  ansible.builtin.include_tasks:
    file: ../tasks/node_exporter.yml


- name: Install unbound exporter
  ansible.builtin.include_tasks:
    file: ../tasks/unbound_exporter.yml


# vim: ft=yaml.ansible
