- name: Ensure required packages are installed
  become: true
  ansible.builtin.apt:
    pkg:
      - nfs-kernel-server
      - rpcbind


- name: Configure exports
  become: true
  ansible.builtin.copy:
    dest: /etc/exports
    content: |
      /opt/data/music 192.168.2.0/24(ro,no_subtree_check)
    owner: root
    group: admin
    mode: '0664'


- name: Ensure nfs-server is running
  become: true
  ansible.builtin.service:
    name: nfs-server
    state: started
    enabled: true

# vim: ft=yaml.ansible
