- name: Install Apt Keys
  become: true
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp.asc
    owner: root
    group: root
    mode: "0644"


- name: Add Apt Repository
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/hashicorp.list
    owner: root
    group: root
    mode: "0644"
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main


- name: Install Vault
  become: true
  ansible.builtin.apt:
    name: vault
    state: present
    update_cache: true


- name: Configure vault
  become: true
  ansible.builtin.copy:
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
    mode: '0664'
    content: |
      # https://developer.hashicorp.com/vault/docs/configuration

      ui = true

      storage "file" {
        path = "/opt/vault/data"
      }

      # https://merry:8200/
      listener "tcp" {
        address       = "0.0.0.0:8200"
        tls_cert_file = "/opt/vault/tls/tls.crt"
        tls_key_file  = "/opt/vault/tls/tls.key"
      }
  notify:
    - Restart vault


- name: Ensure vault is running
  become: true
  ansible.builtin.service:
    name: vault
    state: started
    enabled: true

# vim: ft=yaml.ansible
