# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-14.1-RELEASE"
  config.vm.box_version = "2024.05.31"
  config.vm.hostname = "erebor"
  config.vm.define "erebor"

  # keep on getting issues with the sync folder
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "erebor"
    vb.memory = "2048"
    vb.cpus   = 2
  end
end
