# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://portal.cloud.hashicorp.com/vagrant/discover?providers=libvirt&query=freebsd
  config.vm.box = "bento/freebsd-14"
  config.vm.box_version = "202508.03.0"
  config.vm.hostname = "erebor"
  config.vm.define "erebor"
  config.vm.synced_folder ".", "/vagrant", disabled: false
end
