- name: Install certbot package
  ansible.builtin.apt:
    name: certbot

# I've elected to disable automated renewals. This requires different
# logic for renewing a certificate than creating new a new one. Rather
# than renew certificates, I use the e-mail notification from letsencrypt
# as cue to repave the PI. This ensures that the bootstrapping process
# just works.
#
# ref: https://eff-certbot.readthedocs.io/en/stable/using.html#automated-renewals
- name: Disable certbot.timer
  ansible.builtin.service:
    name: certbot.timer
    enabled: false
    state: stopped


# Nginx needs to be stopped so certbot --standalone can bind to port 80 to
# fulfill the ACME challenges. This code only needs to be uncommented when
# adding a new FQDN. It can be left commented out for the initial run.
# TODO: uncomment this and run it based on a configuration flag
# - name: Ensure nginx is stopped before certbot interactions
#   ansible.builtin.service:
#     name: nginx
#     state: stopped


# In order for this task to work, the FQDNs need to have dns records set
# to my home IP address, and port 80 needs to be forwarded to the PI from
# the router.
# TODO: inject fqdns from the playbook
- name: Acquire certificates
  # This breaks when making it a full qualified module name
  command: |
    certbot certonly --standalone --non-interactive --agree-tos
    -d {{ item.fqdn }} \
    -m {{ item.email }}
  args:
    creates: /etc/letsencrypt/live/{{ item.fqdn }}/fullchain.pem
  loop:
    - fqdn: www.goodenoughmoney.com
      email: "scottmuc@gmail.com"
    - fqdn: home.scottmuc.com
      email: "scottmuc@gmail.com"
