- name: Install unbound package
  ansible.builtin.apt:
    name: unbound

- name: Allow local LAN to connect to unbound
  become: true
  ansible.builtin.copy:
    dest: /etc/unbound/unbound.conf.d/pi-hole-replacement.conf
    owner: root
    group: root
    mode: '0664'
    content: |
      server:
        interface: 0.0.0.0
        access-control: 192.168.2.0/24 allow
        do-ip6: no
        include: /etc/unbound/blocklist.conf
  notify:
    - Restart unbound


- name: Add blocklist
  become: true
  ansible.builtin.get_url:
    dest: /etc/unbound/blocklist.conf
    owner: root
    group: root
    mode: '0664'
    url: https://raw.githubusercontent.com/scottmuc/dns-zone-blocklist/main/unbound/unbound.blocklist
  notify:
    - Restart unbound


- name: Ensure unbound is running
  ansible.builtin.service:
    name: unbound
    state: started
    enabled: true

# vim: ft=yaml.ansible
