- name: Install fail2ban package
  ansible.builtin.apt:
    name: fail2ban


- name: Install iptables package
  ansible.builtin.apt:
    name: iptables


- name: Ensure fail2ban is running
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
# vim: ft=yaml.ansible
