- name: Install packages
  become: true
  ansible.builtin.apt:
    name:
      - loki
      - promtail
    state: present

- name: Install loki configuration
  become: true
  ansible.builtin.copy:
    src: root/etc/loki/config.yml
    dest: /etc/loki/config.yml
    owner: root
    group: admin
    mode: '0664'
  notify:
    - Restart loki


- name: Ensure loki service is running
  become: true
  ansible.builtin.service:
    name: loki
    state: started
    enabled: true


- name: Add promtail to log groups
  become: true
  ansible.builtin.user:
    name: promtail
    groups: adm
    append: true


- name: Install promtail configuration
  become: true
  ansible.builtin.copy:
    src: root/etc/promtail/config.yml
    dest: /etc/promtail/config.yml
    owner: root
    group: admin
    mode: '0664'
  notify:
    - Restart promtail


- name: Ensure promtail service is running
  become: true
  ansible.builtin.service:
    name: promtail
    state: started
    enabled: true

# vim: ft=yaml.ansible
