- name: Create USB mount for persistent storage for services
  become: true
  ansible.builtin.file:
    path: /mnt/vcapstore
    state: directory
    owner: root
    group: root
    mode: '0777'


- name: Mount 32GB disk
  become: true
  ansible.posix.mount:
    state: mounted
    path: /mnt/vcapstore
    src: UUID=e15af423-34a5-445c-978b-c85288f3a90b
    fstype: ext4


- name: Install mount dependencies
  become: true
  ansible.builtin.apt:
    pkg:
      - nfs-common


- name: Create mount for music share
  become: true
  ansible.builtin.file:
    path: /mnt/music
    state: directory
    owner: root
    group: root
    mode: '0555'


- name: Mount music share from merry
  become: true
  ansible.posix.mount:
    src: merry.middle-earth.internal:/opt/data/music
    path: /mnt/music
    fstype: nfs
    state: mounted
    opts: auto,nofail,noatime,nolock,intr,tcp,actimeo=1800

# vim: ft=yaml.ansible
