- name: Install nginx package
  ansible.builtin.apt:
    name: nginx


# Favouring complete overwrite of the configuration file coming from the
# package manager due to reasons identified here:
# https://serverfault.com/questions/825363/override-default-nginx-http-configuration-without-changing-default-nginx-conf
- name: Nginx configuration
  ansible.builtin.copy:
    src: root/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: admin
    mode: '0664'
  notify:
    - Restart nginx


- name: Enable stub_status
  ansible.builtin.copy:
    src: root/etc/nginx/conf.d/status.conf
    dest: /etc/nginx/conf.d/status.conf
    owner: root
    group: admin
    mode: '0664'
  notify:
    - Restart nginx


# Are there trade-offs when ensuring a started and enabled state
# in the same task?
- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
