# If this fails, it's likely due to user level systemd services running. A
# reboot will resolve it... will look into more elegant ways later.
- name: Delete the 'bootstrap' bootstrap user
  become: true
  ansible.builtin.user:
    name: boostrap
    state: absent
    remove: true


# https://linuxhandbook.com/ssh-hardening-tips/
- name: Harden the sshd Configuration
  become: true
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/ssh_hardening.conf
    owner: root
    group: root
    mode: '0664'
    content: |
      PermitEmptyPasswords no
      PasswordAuthentication no
      PermitRootLogin no
      Protocol 2
      X11Forwarding no
  notify:
    - Reload sshd


# vim: ft=yaml.ansible
