- name: Uninstall isc-dhcp-client
  become: true
  ansible.builtin.apt:
    name: isc-dhcp-client
    state: absent


- name: Setup static IP
  become: true
  ansible.builtin.copy:
    dest: /etc/network/interfaces.d/eth0
    owner: root
    group: admin
    mode: '0664'
    content: |
      auto eth0
      allow-hotplug eth0
      iface eth0 inet static
      address 192.168.2.10
      netmask 255.255.255.0
      gateway 192.168.2.1
      dns-nameservers 127.0.0.1
      dns-search middle-earth.internal


- name: Install /etc/resolv.conf
  become: true
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      search middle-earth.internal
      nameserver 192.168.2.10


- name: Install /etc/hosts
  become: true
  ansible.builtin.copy:
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
    content: |
      127.0.0.1     localhost
      192.168.2.10  pippin.middle-earth.internal  pippin

# vim: ft=yaml.ansible
