- name: Uninstall isc-dhcp-client
  become: true
  ansible.builtin.apt:
    name: isc-dhcp-client
    state: absent


- name: Setup static IP
  become: true
  ansible.builtin.copy:
    dest: /etc/network/interfaces.d/eth0
    owner: root
    group: admin
    mode: '0664'
    content: |
      auto eth0
      allow-hotplug eth0
      iface eth0 inet static
      address 192.168.2.10
      netmask 255.255.255.0
      gateway 192.168.2.1
      dns-nameservers 127.0.0.1
      dns-search middle-earth.internal


- name: Install resolv.conf
  become: true
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    owner: root
    group: admin
    mode: '0664'
    content: |
      search middle-earth.internal
      nameserver 127.0.0.1


- name: Add names for all static host assignments
  become: true
  ansible.builtin.copy:
    dest: /etc/unbound/unbound.conf.d/middle-earth.internal.conf
    owner: root
    group: root
    mode: '0664'
    content: |
      server:
        local-data: "pippin.middle-earth.internal.     IN    A   192.168.2.10"
        local-data: "gandalf.middle-earth.internal.    IN    A   192.168.2.12"
        local-data: "denethor.middle-earth.internal.   IN    A   192.168.2.13"
        local-data: "sam.middle-earth.internal.        IN    A   192.168.2.14"
        local-data: "frodo.middle-earth.internal.      IN    A   192.168.2.15"
        local-data: "kili.middle-earth.internal.       IN    A   192.168.2.16"
        local-data: "fili.middle-earth.internal.       IN    A   192.168.2.17"
        local-data: "sauron.middle-earth.internal.     IN    A   192.168.2.18"
        local-data: "treebeard.middle-earth.internal.  IN    A   192.168.2.19"
        local-data: "palantir.middle-earth.internal.   IN    A   192.168.2.20"
        local-data: "elrond.middle-earth.internal.     IN    A   192.168.2.21"
        local-data: "gollum.middle-earth.internal.     IN    A   192.168.2.22"
  notify:
    - Restart unbound

# vim: ft=yaml.ansible
