#!/usr/bin/env bash

set -e
set -o pipefail

main() {
  local sub_command
  sub_command="$1"
  case "$sub_command" in
    unlock)
      base64_key="$(op read op://Automation/infrastructure-git-crypt-key/git-crypt-key)"
      git-crypt unlock <(echo "${base64_key}" | base64 --decode -)
      ;;
    lock)
      git-crypt lock
      ;;
    status)
      if git-crypt export-key /dev/null 2>/dev/null; then
        echo "unlocked"
      else
        echo "locked"
        exit 1
      fi
      ;;
    *)
      print_usage_and_exit
      ;;
  esac
}

print_usage_and_exit() {
  cat <<HELP
usage: $0 <command>

Manages the locking of this repository

Commands:
 - unlock
     decrypts the contents defined in .gitattributes

 - lock
     encrypts the contents defined in .gitattributes

 - status
     prints locked/unlocked

HELP

  exit 1
}

main "$@"
