#!/usr/bin/env bash

set -e
set -o pipefail

main() {
  local sub_command
  sub_command="$1"
  case "$sub_command" in
    unlock)
      # depends on this machine having the following in the PATH
      # https://github.com/scottmuc/infrastructure/blob/master/homedirs/osx/bin/easy-op
      base64_key="$(easy-op show infrastructure-git-crypt-key git-crypt-key)"
      git-crypt unlock <(echo "${base64_key}" | base64 --decode -)
      ;;
    lock)
      git-crypt lock
      ;;
    status)
      echo "not completed"
      ;;
    *)
      print_usage_and_exit
      ;;
  esac
}

print_usage_and_exit() {
  cat <<HELP
usage: $0 <command>

Manages the locking of this repository

Commands:
 - unlock
     decrypts the contents defined in .gitattributes

 - lock
     encrypts the contents defined in .gitattributes

 - stauts
     prints locked/unlocked

HELP

  exit 1
}

main "$@"
