#!/usr/bin/env bash

set -e

# depends on this machine having the following in the PATH
# https://github.com/scottmuc/infrastructure/blob/master/homedirs/osx/bin/easy-op
base64_key="$(easy-op show infrastructure-git-crypt-key git-crypt-key)"
git-crypt unlock <(echo "${base64_key}" | base64 --decode -)
