resources:
- name: infrastructure
  type: git
  icon: github
  source:
    uri: https://github.com/scottmuc/infrastructure


- name: upstream-cachix-flakes
  type: registry-image
  icon: docker
  source:
    repository: docker.nix-community.org/nixpkgs/cachix-flakes
    tag: latest


jobs:
- name: vendor-registry-images
  public: true
  plan:
  - get: upstream-cachix-flakes
    params:
      format: oci

  - task: inspect
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
        - name: upstream-cachix-flakes
      run:
        path: sh
        args:
          - -c
          - |
            tar -tvf upstream-cachix-flakes/image.tar | head -30

  - task: convert-and-push
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: quay.io/skopeo/stable
      inputs:
        - name: upstream-cachix-flakes
      run:
        path: skopeo
        args:
          - copy
          - --format=oci
          - docker-archive:upstream-cachix-flakes/image.tar
          - docker://zot.scottmuc.com/cachix-flakes:latest


- name: static-analysis
  public: true

  plan:
  - get: infrastructure
    trigger: true

  - across:
    - var: script
      values:
      - bin/ansible-checks.sh
      - bin/nix-checks.sh
      - bin/shell-checks.sh
      - bin/terraform-checks.sh
    task: running-((.:script))
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: zot.scottmuc.com/cachix-flakes
      inputs:
      - name: infrastructure
      run:
        path: bin/cachix-ci-nix-wrapper.sh
        dir: infrastructure
        args:
          - "((.:script))"
      params:
        CACHIX_AUTH_TOKEN: ((nix.cachix_token))
