resources:
- name: infrastructure
  type: git
  icon: github
  source:
    uri: https://github.com/scottmuc/infrastructure


- name: bootstrapped-skopeo
  type: registry-image
  icon: docker
  source:
    repository: zot.scottmuc.com/skopeo
    tag: latest


- name: upstream-cachix-flakes
  type: registry-image
  icon: docker
  source:
    repository: docker.nix-community.org/nixpkgs/cachix-flakes
    tag: latest


- name: cachix-flakes
  type: registry-image
  icon: docker
  source:
    repository: zot.scottmuc.com/cachix-flakes
    tag: latest


jobs:
- name: vendor-registry-images
  public: true
  plan:
  - get: upstream-cachix-flakes
    trigger: true
    params:
      format: oci

  - get: bootstrapped-skopeo
    trigger: true

  - task: convert-and-push
    image: bootstrapped-skopeo
    config:
      platform: linux
      inputs:
        - name: upstream-cachix-flakes
      run:
        path: skopeo
        args:
          - copy
          - docker-archive:upstream-cachix-flakes/image.tar
          - docker://zot.scottmuc.com/cachix-flakes:latest


- name: static-analysis
  public: true

  plan:
  - get: infrastructure
    trigger: true

  - get: cachix-flakes
    trigger: true

  - across:
    - var: script
      values:
      - bin/ansible-checks.sh
      - bin/nix-checks.sh
      - bin/shell-checks.sh
      - bin/terraform-checks.sh
    task: running-((.:script))
    image: cachix-flakes
    config:
      platform: linux
      inputs:
      - name: infrastructure
      run:
        path: bin/cachix-ci-nix-wrapper.sh
        dir: infrastructure
        args:
          - "((.:script))"
      params:
        CACHIX_AUTH_TOKEN: ((nix.cachix_token))
