resources:
- name: infrastructure
  type: git
  icon: github
  source:
    uri: https://github.com/scottmuc/infrastructure

jobs:
- name: static-analysis
  public: true

  plan:
  - get: infrastructure
    trigger: true

  - across:
    - var: script
      values:
      - bin/ansible-checks.sh
      - bin/nix-checks.sh
      - bin/shell-checks.sh
      - bin/terraform-checks.sh
    task: running-((.:script))
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: docker.nix-community.org/nixpkgs/cachix-flakes
      inputs:
      - name: infrastructure
      run:
        path: bin/cachix-ci-nix-wrapper.sh
        dir: infrastructure
        args:
          - "((.:script))"
      params:
        CACHIX_AUTH_TOKEN: ((nix.cachix_token))
