resources:
- name: infrastructure
  type: git
  icon: github
  source:
    uri: https://github.com/scottmuc/infrastructure


- name: bootstrapped-skopeo
  type: registry-image
  icon: docker
  source:
    repository: zot.scottmuc.com/skopeo
    tag: latest


- name: upstream-cachix-flakes
  type: registry-image
  icon: docker
  source:
    repository: docker.nix-community.org/nixpkgs/cachix-flakes
    tag: latest


- name: cachix-flakes
  type: registry-image
  icon: docker
  source:
    repository: zot.scottmuc.com/cachix-flakes
    tag: latest


- name: infrastructure-ci
  type: registry-image
  icon: docker
  source:
    repository: zot.scottmuc.com/infrastructure-ci
    tag: latest


jobs:
- name: build-publish-ci-images
  public: true

  plan:
  - get: infrastructure
  - get: bootstrapped-skopeo
  - get: cachix-flakes

  - task: build-infrastructure-ci-image
    image: cachix-flakes
    config:
      platform: linux
      inputs:
      - name: infrastructure
      outputs:
      - name: result
      run:
        path: sh
        args:
          - -c
          - |
            cachix use scottmuc

            cachix watch-exec scottmuc -- \
              nix --extra-experimental-features "nix-command flakes" \
              build ./infrastructure#ci-image -o result/image
              # Create a local filesystem reference because /nix/store
              # doesn't persist across steps.
              cp result/image result/image.tar.gz
              (cd result && gunzip image.tar.gz)
      params:
        CACHIX_AUTH_TOKEN: ((nix.cachix_token))


  - task: convert-and-push
    image: bootstrapped-skopeo
    config:
      platform: linux
      inputs:
      - name: result
      run:
        path: skopeo
        args:
          - copy
          - --format=oci
          - docker-archive:result/image.tar
          - docker://zot.scottmuc.com/infrastructure-ci:latest


- name: vendor-registry-images
  public: true
  plan:
  - get: upstream-cachix-flakes
    trigger: true
    params:
      format: oci

  - get: bootstrapped-skopeo
    trigger: true

  - task: convert-and-push
    image: bootstrapped-skopeo
    config:
      platform: linux
      inputs:
        - name: upstream-cachix-flakes
      run:
        path: skopeo
        args:
          - copy
          - docker-archive:upstream-cachix-flakes/image.tar
          - docker://zot.scottmuc.com/cachix-flakes:latest


- name: static-analysis
  public: true

  plan:
  - get: infrastructure
    trigger: true

  - get: infrastructure-ci
    trigger: true

  - across:
    - var: script
      values:
      - bin/ansible-checks.sh
      - bin/nix-checks.sh
      - bin/shell-checks.sh
      - bin/terraform-checks.sh
    task: running-((.:script))
    image: infrastructure-ci
    config:
      platform: linux
      inputs:
      - name: infrastructure
      run:
        path: "((.:script))"
        dir: infrastructure
