#!/usr/bin/env bash

set -e
set -u

# from https://stackoverflow.com/a/246128
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
LIB_DIR="${DIR}/../common/lib"

# shellcheck disable=SC1091
source "${LIB_DIR}/install_asdf.bash"

main() {
  symlink_all_the_things
  write_or_check_machine_birthdate
  disable_ipv6
  set_clock_format
  set_dock_preferences
  invoke_homebrew
  configure_tap_to_click
  install_asdf
}


# I am getting the absolute path so that ls -la output goes from:
#
#   .config -> /Users/spring/workspace/infrastructure/homedirs/osx/bin/../dotfiles/dot.config
# to
#   .config -> /Users/spring/workspace/infrastructure/homedirs/osx/dotfiles/dot.config
symlink_all_the_things() {
  local homedir_source common_source dotfiles_dir common_dotfiles_dir
  homedir_source=$(cd "${DIR}/"; pwd)
  common_source=$(cd "${DIR}/../common"; pwd)
  dotfiles_dir="${homedir_source}/dotfiles"
  common_dotfiles_dir="${common_source}/dotfiles"

  # I don't know how to do this command in a 1 line indempotent way. Repeated executions
  # but symlinks within the symlink.
  if [[ ! -d ~/.config ]]; then
    mkdir ~/.config
  fi

  if [[ ! -d ~/.gnupg ]]; then
    mkdir ~/.gnupg
    chmod 700 ~/.gnupg
  fi
  ln -sfv "${common_dotfiles_dir}/dot.gnupg/gpg-agent.conf" ~/.gnupg/gpg-agent.conf

  ln -sfv "${common_dotfiles_dir}/dot.githelpers" ~/.githelpers
  ln -sfv "${common_dotfiles_dir}/dot.tmux.conf" ~/.tmux.conf
  ln -sfv "${common_dotfiles_dir}/dot.gitconfig" ~/.gitconfig
  ln -sfv "${common_dotfiles_dir}/dot.mrconfig" ~/.mrconfig

  # https://ss64.com/osx/ln.html the -h is important to not put a symlink in a dir symlink
  ln -shfv "${common_dotfiles_dir}/dot.config/nvim" ~/.config/nvim

  ln -sfv "${dotfiles_dir}/dot.zshrc" ~/.zshrc
}

write_or_check_machine_birthdate() {
  local birthdate_file
  local birthdate

  birthdate_file=~/.birthdate
  if [ ! -f "${birthdate_file}" ]
  then
    date > "${birthdate_file}"
  else
    birthdate="$(cat ${birthdate_file})"
    echo "Your machine was born on: ${birthdate}"
    echo ""
    echo "Have you considered that it might be time to recreate your workstation?"
    sleep 5
  fi
}

# With IPv6 enabled my /etc/resolv.conf looks like the following:
# search middle-earth.internal
# nameserver fe80::1
# nameserver 192.168.2.10
#
# The first address is my router and it has a crappy slow DNS resolver. Since
# my air is only on Wi-Fi, I'm disabling it on that interface only.
disable_ipv6() {
  sudo networksetup -setv6off Wi-Fi
}

# Instruction manual:
#   https://www.tech-otaku.com/mac/setting-the-date-and-time-format-for-the-macos-menu-bar-clock-using-terminal/
set_clock_format() {
  defaults write "com.apple.menuextra.clock" "DateFormat" -string "MMM d  HH:mm:ss"
  killall SystemUIServer
}

set_dock_preferences() {
  defaults write "com.apple.dock" "orientation" -string "left"
  defaults write "com.apple.dock" "autohide" -bool "true"
  # clears all the stuff I don't need or want
  defaults write "com.apple.dock" "persistent-apps" -array
  killall Dock
}

invoke_homebrew() {
  if [ ! -x /usr/local/bin/brew ]
  then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  else
    brew update || true
  fi

  brew bundle --file=./Brewfile
}


# copied from:
# - https://github.com/mathiasbynens/dotfiles/blob/master/.macos#L147-L150
# - http://osxdaily.com/2014/01/31/turn-on-mac-touch-to-click-command-line/
configure_tap_to_click() {
  defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
  defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
  defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
}

main
